
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD LPAR MULT NUM RPARexpression : expression MULT mid_prioexpression : mid_priomid_prio : mid_prio ADD top_priomid_prio : top_priotop_prio : LPAR expression RPARtop_prio : NUM'
    
_lr_action_items = {'LPAR':([0,4,6,7,],[4,4,4,4,]),'NUM':([0,4,6,7,],[5,5,5,5,]),'$end':([1,2,3,5,9,10,11,],[0,-2,-4,-6,-1,-3,-5,]),'MULT':([1,2,3,5,8,9,10,11,],[6,-2,-4,-6,6,-1,-3,-5,]),'RPAR':([2,3,5,8,9,10,11,],[-2,-4,-6,11,-1,-3,-5,]),'ADD':([2,3,5,9,10,11,],[7,-4,-6,7,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,],[1,8,]),'mid_prio':([0,4,6,],[2,2,9,]),'top_prio':([0,4,6,7,],[3,3,3,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression MULT mid_prio','expression',3,'p_expression_mult','18.py',61),
  ('expression -> mid_prio','expression',1,'p_expression_mid','18.py',66),
  ('mid_prio -> mid_prio ADD top_prio','mid_prio',3,'p_mid_sum','18.py',70),
  ('mid_prio -> top_prio','mid_prio',1,'p_mid_top','18.py',75),
  ('top_prio -> LPAR expression RPAR','top_prio',3,'p_term_parens','18.py',79),
  ('top_prio -> NUM','top_prio',1,'p_term_num','18.py',84),
]
